[pytest]
DJANGO_SETTINGS_MODULE = alphafx.settings.base
testpaths = code/backend/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --tb=short
pythonpath = code/backend
