apiVersion: v1
kind: ServiceAccount
metadata:
  name: alphafx
  namespace: alphafx
  labels:
    app.kubernetes.io/name: alphafx
    app.kubernetes.io/component: rbac
automountServiceAccountToken: false
